INSERT INTO STORY VALUES (SEQUENCE_STORY_B_NO.NEXTVAL, '1111', 'TEST TEST TEST TEST TEST TEST1', 'test001', DEFAULT, SYSDATE, 1, DEFAULT);
INSERT INTO STORY VALUES (SEQUENCE_STORY_B_NO.NEXTVAL, '2222', 'TEST TEST TEST TEST TEST TEST2', 'test002', DEFAULT, SYSDATE, 1, DEFAULT);
INSERT INTO STORY VALUES (SEQUENCE_STORY_B_NO.NEXTVAL, '3333', 'TEST TEST TEST TEST TEST TEST3', 'test003', DEFAULT, SYSDATE, 3, DEFAULT);
INSERT INTO STORY VALUES (SEQUENCE_STORY_B_NO.NEXTVAL, '4444', 'TEST TEST TEST TEST TEST TEST3', 'test003', DEFAULT, SYSDATE, 4, DEFAULT);
INSERT INTO STORY VALUES (SEQUENCE_STORY_B_NO.NEXTVAL, '4444', 'TEST TEST TEST TEST TEST TEST3', 'test003', DEFAULT, SYSDATE, 4, DEFAULT);
INSERT INTO STORY VALUES (SEQUENCE_STORY_B_NO.NEXTVAL, '5555', 'TEST TEST TEST TEST TEST TEST3', 'test003', DEFAULT, SYSDATE, 5, DEFAULT);
INSERT INTO STORY VALUES (SEQUENCE_STORY_B_NO.NEXTVAL, '6666', 'TEST TEST TEST TEST TEST TEST3', 'test003', DEFAULT, SYSDATE, 6, DEFAULT);
INSERT INTO STORY VALUES (SEQUENCE_STORY_B_NO.NEXTVAL, '7777', 'TEST TEST TEST TEST TEST TEST3', 'test003', DEFAULT, SYSDATE, 7, DEFAULT);

SELECT * FROM MEMBER;
select * from STORY;

INSERT INTO FREE VALUES (SEQUENCE_FREE_B_NO.NEXTVAL, '1111', 'TEST TEST TEST TEST TEST TEST1', 'test001', DEFAULT, SYSDATE, DEFAULT);
INSERT INTO FREE VALUES (SEQUENCE_FREE_B_NO.NEXTVAL, '1111', 'TEST TEST TEST TEST TEST TEST2', 'test001', DEFAULT, SYSDATE, DEFAULT);
INSERT INTO FREE VALUES (SEQUENCE_FREE_B_NO.NEXTVAL, '1111', 'TEST TEST TEST TEST TEST TEST2', 'test002', DEFAULT, SYSDATE, DEFAULT);
INSERT INTO FREE VALUES (SEQUENCE_FREE_B_NO.NEXTVAL, '1111', 'TEST TEST TEST TEST TEST TEST3', 'test003', DEFAULT, SYSDATE, DEFAULT);
INSERT INTO FREE VALUES (SEQUENCE_FREE_B_NO.NEXTVAL, '1111', 'TEST TEST TEST TEST TEST TEST4', 'test004', DEFAULT, SYSDATE, DEFAULT);
INSERT INTO FREE VALUES (SEQUENCE_FREE_B_NO.NEXTVAL, '1111', 'TEST TEST TEST TEST TEST TEST5', 'test005', DEFAULT, SYSDATE, DEFAULT);
INSERT INTO FREE VALUES (SEQUENCE_FREE_B_NO.NEXTVAL, '1111', 'TEST TEST TEST TEST TEST TEST6', 'test005', DEFAULT, SYSDATE, DEFAULT);
INSERT INTO FREE VALUES (SEQUENCE_FREE_B_NO.NEXTVAL, '1111', 'TEST TEST TEST TEST TEST TEST7', 'test005', DEFAULT, SYSDATE, DEFAULT);

SELECT * FROM FREE;

INSERT INTO STORY_RECOMMENT VALUES (SEQUENCE_STORY_R_NO.NEXTVAL, 4, 'test002', 'TEST TEST TEST TEST TEST121', DEFAULT);
INSERT INTO STORY_RECOMMENT VALUES (SEQUENCE_STORY_R_NO.NEXTVAL, 5, 'test003', 'TEST TEST TEST TEST TEST121', DEFAULT);
INSERT INTO STORY_RECOMMENT VALUES (SEQUENCE_STORY_R_NO.NEXTVAL, 5, 'test003', 'TEST TEST TEST TEST TEST121', DEFAULT);
INSERT INTO STORY_RECOMMENT VALUES (SEQUENCE_STORY_R_NO.NEXTVAL, 7, 'test004', 'TEST TEST TEST TEST TEST121', DEFAULT);
INSERT INTO STORY_RECOMMENT VALUES (SEQUENCE_STORY_R_NO.NEXTVAL, 8, 'test005', 'TEST TEST TEST TEST TEST121', DEFAULT);
INSERT INTO STORY_RECOMMENT VALUES (SEQUENCE_STORY_R_NO.NEXTVAL, 1, 'test002', 'TEST TEST TEST TEST TEST121', DEFAULT);

SELECT * FROM STORY_RECOMMENT;

INSERT INTO FREE_RECOMMENT VALUES (SEQUENCE_FREE_R_NO.NEXTVAL, 5, 'test003', 'TEST TEST TEST TEST453', DEFAULT);
INSERT INTO FREE_RECOMMENT VALUES (SEQUENCE_FREE_R_NO.NEXTVAL, 3, 'test004', 'TEST TEST TEST TEST453', DEFAULT);
INSERT INTO FREE_RECOMMENT VALUES (SEQUENCE_FREE_R_NO.NEXTVAL, 4, 'test002', 'TEST TEST TEST TEST452', DEFAULT);
INSERT INTO FREE_RECOMMENT VALUES (SEQUENCE_FREE_R_NO.NEXTVAL, 6, 'test004', 'TEST TEST TEST TEST451', DEFAULT);
INSERT INTO FREE_RECOMMENT VALUES (SEQUENCE_FREE_R_NO.NEXTVAL, 3, 'test004', 'TEST TEST TEST TEST453', DEFAULT);
INSERT INTO FREE_RECOMMENT VALUES (SEQUENCE_FREE_R_NO.NEXTVAL, 2, 'test005', 'TEST TEST TEST TEST453', DEFAULT);

SELECT * FROM FREE_RECOMMENT;