DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE RECOMMENT CASCADE CONSTRAINTS;
DROP TABLE CART CASCADE CONSTRAINTS;
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE OPTION_PARENT CASCADE CONSTRAINTS;
DROP TABLE ORDER_DETAIL CASCADE CONSTRAINTS;
DROP TABLE CART_DETAIL CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_DETAIL CASCADE CONSTRAINTS;
DROP TABLE BOARD_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_IMG CASCADE CONSTRAINTS;

CREATE TABLE Member (
	M_ID	VARCHAR2(20)		NOT NULL,
	M_PW	VARCHAR2(20)		NOT NULL,
	M_NAME	VARCHAR2(20)		NOT NULL,
	M_NICKNAME	VARCHAR2(20)		NOT NULL,
	M_PHONE	VARCHAR2(20)		NOT NULL,
	M_GRADE	NUMBER		NOT NULL,
	M_NY	VARCHAR2(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN Member.M_GRADE IS '사용자등급';
COMMENT ON COLUMN Member.M_ID IS '아이디';
COMMENT ON COLUMN Member.M_NY IS '탈퇴여부';
COMMENT ON COLUMN member.m_grade is '사용자등급';

CREATE TABLE Product_Category (
	CATEGORY_ID	NUMBER		NOT NULL,
	CATEGORY_NAME	VARCHAR2(10)		NOT NULL
);

CREATE TABLE Board (
	B_NO	VARCHAR2(20)		NOT NULL,
	B_ID	VARCHAR2(20)		NOT NULL,
	B_TITLE	VARCHAR2(50)		NOT NULL,
	B_CONTENT	VARCHAR2(300)		NOT NULL,
	M_ID	VARCHAR2(20)		NOT NULL,
	B_CNT	Number		NOT NULL,
	B_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	B_NY	VARCHAR(1)	DEFAULT 'Y'	NOT NULL
);


COMMENT ON COLUMN Board.B_ID IS '1. 스토리 2. 자유게시판';

COMMENT ON COLUMN Board.B_NY IS 'N 비공개 /  Y 공개';

CREATE TABLE Recomment (
	R_NO	VARCHAR2(20)		NOT NULL,
	B_NO	VARCHAR2(20)		NOT NULL,
	B_ID	VARCHAR2(20)		NOT NULL,
	M_ID	VARCHAR2(20)		NOT NULL,
	R_CONTENT	VARCHAR2(100)		NOT NULL,
	R_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN Recomment.B_ID IS '1. 스토리 2. 자유게시판';


CREATE TABLE Cart (
	C_NO	VARCHAR2(10)		NOT NULL,
	M_ID	VARCHAR2(20)		NOT NULL
);


CREATE TABLE Orders (
	O_NO	VARCHAR2(20)		NOT NULL,
	M_ID	VARCHAR2(20)		NOT NULL,
	O_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	O_NAME	VARCHAR2(20)		NOT NULL,
	O_EMAIL	VARCHAR2(50)		NULL,
	O_PHONE	VARCHAR2(20)		NOT NULL,
	O_RECEIVER	VARCHAR2(20)		NOT NULL,
	O_RECEIVER_ADDRESS	VARCHAR2(300)		NOT NULL,
	O_RECEIVER_PHONE	VARCHAR2(20)		NOT NULL
);


CREATE TABLE Product (
	P_NO	VARCHAR2(20)		NOT NULL,
	P_NAME	VARCHAR2(50)		NOT NULL,
	P_CONTENT	VARCHAR2(300)		NOT NULL,
	P_PRICE	NUMBER		NOT NULL,
	CATEGORY_ID	NUMBER		NOT NULL
);


CREATE TABLE Option_Parent (
	OPT_NO	VARCHAR2(20)		NOT NULL,
	OPT_NAME	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN Option_Parent.OPT_NO IS '1, 2';

COMMENT ON COLUMN Option_Parent.OPT_NAME IS '색상, 사이즈';


CREATE TABLE Order_Detail (
	O_DETAIL_NO	VARCHAR2(20)		NOT NULL,
	P_SEQ	VARCHAR2(20)		NOT NULL,
	O_DETAIL_CNT	NUMBER		NOT NULL
);



CREATE TABLE Cart_Detail (
	C_NO	VARCHAR2(10)		NOT NULL,
	P_SEQ	VARCHAR2(20)		NOT NULL,
	C_DETAIL_CNT	Number		NOT NULL
);


CREATE TABLE Product_Detail (
	P_SEQ	VARCHAR2(20)		NOT NULL,
	P_NO	VARCHAR2(20)		NOT NULL,
	OPT_NO	VARCHAR2(20)		NOT NULL,
	OPT_VAL	VARCHAR2(20)		NOT NULL,
	P_PRICE	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN Product_Detail.OPT_NO IS '1, 2';

CREATE TABLE Board_Category (
	B_ID	VARCHAR2(20)		NOT NULL,
	B_Name	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN Board_Category.B_ID IS '1. 스토리 2. 자유게시판';

CREATE TABLE Product_Img (
	PRODUCT_IMG_NO	VARCHAR2(20)		NOT NULL,
	P_NO	VARCHAR2(20)		NOT NULL,
	PRODUCT_IMG_NAME	VARCHAR2(300)		NOT NULL,
	PRODUCT_IMG_SIZE	NUMBER		NOT NULL
);

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	M_ID
);

ALTER TABLE Product_Category ADD CONSTRAINT PK_PRODUCT_CATEGORY PRIMARY KEY (
	CATEGORY_ID
);

ALTER TABLE Board ADD CONSTRAINT PK_BOARD PRIMARY KEY (
	B_NO,
	B_ID
);

ALTER TABLE Recomment ADD CONSTRAINT PK_RECOMMENT PRIMARY KEY (
	R_NO,
	B_NO,
	B_ID
);

ALTER TABLE Cart ADD CONSTRAINT PK_CART PRIMARY KEY (
	C_NO
);


ALTER TABLE Orders ADD CONSTRAINT PK_ORDER PRIMARY KEY (
	O_NO
);

ALTER TABLE Product ADD CONSTRAINT PK_PRODUCT PRIMARY KEY (
	P_NO
);

ALTER TABLE Option_Parent ADD CONSTRAINT PK_OPTION_PARENT PRIMARY KEY (
	OPT_NO
);

ALTER TABLE Order_Detail ADD CONSTRAINT PK_ORDER_DETAIL PRIMARY KEY (
	O_DETAIL_NO,
	P_SEQ
);

ALTER TABLE Cart_Detail ADD CONSTRAINT PK_CART_DETAIL PRIMARY KEY (
	C_NO,
	P_SEQ
);

ALTER TABLE Product_Detail ADD CONSTRAINT PK_PRODUCT_DETAIL PRIMARY KEY (
	P_SEQ
);

ALTER TABLE Board_Category ADD CONSTRAINT PK_BOARD_CATEGORY PRIMARY KEY (
	B_ID
);

ALTER TABLE Product_Img ADD CONSTRAINT PK_PRODUCT_IMG PRIMARY KEY (
	PRODUCT_IMG_NO,
	P_NO
);

ALTER TABLE Board ADD CONSTRAINT FK_Board_Category_TO_Board_1 FOREIGN KEY (
	B_ID
) REFERENCES Board_Category (
	B_ID
);

ALTER TABLE Board ADD CONSTRAINT FK_Member_TO_Board_1 FOREIGN KEY (
	M_ID
)
REFERENCES Member (
	M_ID
);

ALTER TABLE Recomment ADD CONSTRAINT FK_Board_TO_Recomment_1 FOREIGN KEY (
	B_NO, B_ID
)
REFERENCES Board (
	B_NO, B_ID
);

ALTER TABLE Recomment ADD CONSTRAINT FK_Member_Recomment FOREIGN KEY (
	M_ID
)
REFERENCES Member (
	M_ID
);

ALTER TABLE Cart ADD CONSTRAINT FK_Member_TO_Cart_1 FOREIGN KEY (
	M_ID
)
REFERENCES Member (
	M_ID
);

ALTER TABLE Orders ADD CONSTRAINT FK_Member_TO_Order_1 FOREIGN KEY (
	M_ID
)
REFERENCES Member (
	M_ID
);


ALTER TABLE Product ADD CONSTRAINT FK_Prod_Cate_TO_Prod_1 FOREIGN KEY (
	CATEGORY_ID
)
REFERENCES Product_Category (
	CATEGORY_ID
);

ALTER TABLE Order_Detail ADD CONSTRAINT FK_Order_TO_Order_Detail_1 FOREIGN KEY (
	O_DETAIL_NO
)
REFERENCES Orders (
	O_NO
);


ALTER TABLE Order_Detail ADD CONSTRAINT FK_Prod_Detail_TO_Ord_Detail_1 FOREIGN KEY (
	P_SEQ
)
REFERENCES Product_Detail (
	P_SEQ
);

ALTER TABLE Cart_Detail ADD CONSTRAINT FK_Cart_TO_Cart_Detail_1 FOREIGN KEY (
	C_NO
)
REFERENCES Cart (
	C_NO
);

ALTER TABLE Cart_Detail ADD CONSTRAINT FK_Prod_Deta_TO_Cart_Deta_1 FOREIGN KEY (
	P_SEQ
)
REFERENCES Product_Detail (
	P_SEQ
);

ALTER TABLE Product_Detail ADD CONSTRAINT FK_Product_TO_Product_Detail_1 FOREIGN KEY (
	P_NO
)
REFERENCES Product (
	P_NO
);

ALTER TABLE Product_Detail ADD CONSTRAINT FK_Opt_Parent_TO_Prod_Det FOREIGN KEY (
	OPT_NO
)
REFERENCES Option_Parent (
	OPT_NO
);

ALTER TABLE Product_Img ADD CONSTRAINT FK_Product_TO_Product_Img_1 FOREIGN KEY (
	P_NO
)
REFERENCES Product (
	P_NO
);
